import Link from '@/components/app-link';
import { MobileShell, ScreenHeader } from '@/components/mobile-shell';

export const metadata = {
  title: 'Privacy | COSMORA',
  description: 'Informazioni sui dati personali trattati da COSMORA e su come esercitare i tuoi diritti.',
};

const sections = [
  ['Chi gestisce i tuoi dati', 'Il titolare del trattamento è Andrea Gadducci, titolare della ditta individuale Kreluna Software. Puoi contattarci a info@kreluna.it indicando nell’oggetto [COSMORA] Privacy. Questa informativa riguarda il sito e l’app COSMORA.'],
  ['Account e profilo', 'Trattiamo email, identificativo dell’account, credenziali gestite dal servizio di autenticazione, nome pubblico e paese inseriti nel profilo. Se accedi con Apple o Google, riceviamo i dati che il servizio di accesso rende disponibili, come email, nome e immagine del profilo. Non riceviamo la password del tuo account Apple o Google. Questi dati servono a creare e mantenere l’account e a fornire le funzioni richieste, sulla base dell’esecuzione del servizio (art. 6.1.b GDPR). I campi obbligatori sono necessari per la relativa funzione; senza di essi potresti non poterla utilizzare.'],
  ['Community, annunci e messaggi', 'Conserviamo le foto e i video che carichi, le descrizioni dei post e degli annunci, i messaggi, le preferenze salvate, i voti e le partecipazioni alle crew per consentirti di usare queste funzioni. Nome pubblico, paese, post e annunci possono essere visibili anche a visitatori non autenticati. I messaggi sono destinati ai partecipanti alla conversazione; non sono post pubblici. Non inserire dati sensibili o informazioni di altre persone senza una base legittima. I contenuti resi pubblici possono essere copiati da altri: la cancellazione da COSMORA non rimuove automaticamente copie esterne.'],
  ['Venditori e ordini', 'Per il profilo venditore trattiamo i contatti, il paese e i dati commerciali, di fatturazione e consegna che inserisci. Ai negozi vengono richiesti anche dati aziendali e condizioni di vendita. Le funzionalità relative agli ordini registrano i partecipanti, i prodotti, gli importi, gli stati e gli identificativi di pagamento. Nella versione attuale l’integrazione Stripe è in modalità di prova: non rappresenta un servizio di incasso reale né un deposito a garanzia. Quando utilizzi il collegamento Stripe, i dati necessari al conto e alla sessione di pagamento sono trasmessi a Stripe. Non inserire carte o documenti reali nei flussi di prova.'],
  ['Foto, posizione e funzioni facoltative', 'Accediamo ai file che scegli di caricare, non pubblichiamo automaticamente l’intera libreria Foto. Il modulo di rimozione dello sfondo della sezione vendita elabora l’immagine sul dispositivo dopo il download facoltativo del modello; pubblicare successivamente la foto è un’operazione distinta. La mappa OpenStreetMap si carica quando la apri e comunica al fornitore IP e area visualizzata. La posizione GPS viene utilizzata sul dispositivo solo quando la attivi, per mostrare il punto sulla mappa; il componente non salva le coordinate nel database COSMORA. Le richieste cartografiche possono comunque rivelare l’area visualizzata. Puoi revocare i permessi dalle impostazioni del dispositivo e usare le altre funzioni senza GPS.'],
  ['Assistenza e sicurezza', 'Trattiamo i messaggi inviati all’assistenza, le segnalazioni e i blocchi per rispondere alle richieste e contrastare abusi. I controlli automatici sul testo possono sospendere la pubblicazione di un contenuto in attesa di verifica; puoi chiedere un riesame all’assistenza. Le operazioni di sicurezza e moderazione si basano sul legittimo interesse a proteggere utenti e servizio (art. 6.1.f GDPR), fatto salvo il diritto di opposizione. Eventuali adempimenti obbligatori si basano sull’art. 6.1.c GDPR. Non inviare password, codici temporanei o dati completi di carte all’assistenza.'],
  ['Fornitori e dati tecnici', 'Utilizziamo Supabase per autenticazione, database e file, Sites e l’infrastruttura Cloudflare per erogare il sito, e Aruba per la posta di assistenza. Apple, Google, Stripe e OpenStreetMap intervengono quando utilizzi le rispettive funzioni. Le infrastrutture possono trattare IP, richieste e registri tecnici necessari al funzionamento e alla sicurezza. Sul dispositivo vengono conservati dati di sessione e preferenze tecniche, come la lingua. Non utilizziamo questi dati per pubblicità comportamentale. I servizi esterni possono operare in più paesi: non garantiamo che ogni trattamento avvenga esclusivamente nello Spazio economico europeo. Puoi richiedere informazioni sui destinatari e sulle garanzie applicabili a info@kreluna.it.'],
  ['Conservazione e cancellazione', 'Account e contenuti restano conservati finché mantieni l’account o ne richiedi la cancellazione, salvo necessità di gestione di operazioni, contestazioni o obblighi legali. La durata dei dati di assistenza e sicurezza dipende dalla gestione della richiesta o dell’incidente e dalla necessità di tutelare diritti; i log e le copie di backup dipendono anche dal servizio infrastrutturale utilizzato. Non promettiamo cancellazione istantanea da ogni backup. Puoi eliminare l’account dalla funzione dedicata: il flusso rimuove account, contenuti associati e file. Se risultano operazioni reali da gestire, la procedura richiede di contattare l’assistenza. In caso di errore nella cancellazione, scrivici per completare la richiesta.'],
  ['I tuoi diritti', 'Nei casi previsti dal GDPR puoi chiedere accesso, rettifica, cancellazione, limitazione e portabilità dei dati, e opporti ai trattamenti basati sul legittimo interesse. Quando un trattamento si basa sul consenso, puoi revocarlo senza pregiudicare la liceità del trattamento precedente. Scrivi a info@kreluna.it: potremmo chiederti le informazioni strettamente necessarie a verificare la tua identità. Hai diritto di presentare reclamo al Garante per la protezione dei dati personali o all’autorità competente nel tuo paese.'],
  ['Aggiornamenti', 'Aggiorneremo questa informativa se cambiano le funzioni o il trattamento dei dati. In particolare, l’eventuale attivazione di pagamenti reali richiederà informazioni aggiornate prima del loro utilizzo. Ultimo aggiornamento: 7 settembre 2026.'],
];

export default function PrivacyPage() {
  return <MobileShell>
    <ScreenHeader title="Privacy" back="/support" />
    <article lang="it" className="space-y-7 px-5 py-6 text-base leading-relaxed text-white/85">
      <h1 className="text-2xl font-semibold text-white">Informativa sulla privacy</h1>
      {sections.map(([title, text]) => <section key={title} className="space-y-2">
        <h2 className="text-lg font-semibold text-white">{title}</h2><p>{text}</p>
      </section>)}
      <p><a className="text-pink-300 underline" href="mailto:info@kreluna.it?subject=%5BCOSMORA%5D%20Privacy">Contatta il titolare per la privacy</a></p>
      <p><Link className="text-pink-300 underline" href="/account/delete">Elimina il tuo account</Link></p>
      <p><a className="text-pink-300 underline" href="https://www.garanteprivacy.it/">Garante per la protezione dei dati personali</a></p>
    </article>
  </MobileShell>;
}
