import Image from 'next/image';
import Link from '@/components/app-link';
import { Camera, Heart, MapPin, ShieldAlert, ShoppingBag, UsersRound } from 'lucide-react';

import { MobileNav, MobileShell, ScreenHeader } from '@/components/mobile-shell';

export default function LuccaEventPage() {
  return <MobileShell className="flex flex-col"><ScreenHeader title="Lucca Comics & Games 2026" back="/events" action={<Heart className="size-5" />} /><div className="flex-1"><div className="grid grid-cols-4 border-b border-white/10 text-center text-[9px]"><span className="border-b-2 border-pink-400 py-3 text-pink-300">Map</span><span className="py-3 text-white/50">Schedule</span><span className="py-3 text-white/50">Info</span><Link href="/community" className="py-3 text-white/50">Community</Link></div><div className="relative h-[300px]"><Image src="/lucca-map.png" alt="Lucca event map" fill priority sizes="430px" className="object-cover" /></div><div className="space-y-2 px-4 py-3"><h2 className="text-xs font-semibold">Nearby</h2><Nearby icon={ShoppingBag} title="Sellers" meta="42 nearby" images={['/hd-category-cosplay.png','/hd-category-manga.png','/hd-category-cards.png']} /><Nearby icon={Camera} title="Photographers" meta="18 nearby" images={['/category-artist.png','/cosmora-hero.png']} />
    <section className="mt-4"><div className="flex items-center justify-between"><h2 className="text-xs font-semibold">Squads & Meetups</h2><Link href="/squads/create" className="text-[9px] text-pink-300">Create</Link></div><div className="mt-2 grid grid-cols-3 gap-2">{[['48','Cosplay Squads'],['22','Meetups'],['9','Photo Meetups']].map(([count,label]) => <div key={label} className="rounded-xl border border-violet-400/15 bg-violet-400/5 p-2 text-center"><b className="block text-sm text-violet-200">{count}</b><span className="text-[7px] text-white/45">{label}</span></div>)}</div><Link href="/squads/one-piece-crew-lucca-2026" className="mt-2 flex items-center rounded-xl border border-white/8 bg-[#111225] p-2.5"><UsersRound className="mr-3 size-4 text-pink-400" /><div className="flex-1"><p className="text-[10px]">One Piece Crew — Lucca 2026</p><p className="text-[8px] text-white/45">8 / 12 · Looking for characters</p></div><span className="text-white/35">›</span></Link></section>
    <a href="https://www.luccacomicsandgames.com/" target="_blank" rel="noreferrer" className="mt-3 flex h-10 w-full items-center justify-center rounded-xl border border-pink-400/40 text-[10px] text-pink-300">Official site & tickets ↗</a><button className="mt-2 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-pink-500 to-violet-500 text-xs"><ShieldAlert className="size-4" />SOS Cosplay — Get help or assistance</button></div></div><MobileNav active="explore" /></MobileShell>;
}

function Nearby({ icon: Icon, title, meta, images }: { icon: typeof MapPin; title: string; meta: string; images: string[] }) { return <div className="flex items-center rounded-xl border border-white/8 bg-[#111225] p-2.5"><Icon className="mr-3 size-4 text-pink-400" /><div className="flex-1"><p className="text-[10px]">{title}</p><p className="text-[8px] text-white/45">{meta}</p></div><div className="flex -space-x-2">{images.map((src) => <span key={src} className="relative size-7 overflow-hidden rounded-full border-2 border-[#111225]"><Image src={src} alt="" fill sizes="28px" className="object-cover" /></span>)}</div></div>; }
