import type { Locale } from './config';

const en = {
  home: 'COSMORA home', openCommunity: 'Open community', inbox: 'Messages and orders', searchLabel: 'Search COSMORA', searchPlaceholder: 'Products, events, people…', search: 'Search', featured: 'Featured event', ongoing: 'Happening now', discover: 'Explore event', passions: 'Your interests', listings: 'All listings', cosplay: 'Cosplay', comics: 'Manga & comics', figures: 'Action figures', cards: 'Trading cards', gaming: 'Video games', people: 'People & sellers', events: 'Events in Europe', eventsSubtitle: 'Conventions, festivals and meetups', noUpcoming: 'New events coming soon', noUpcomingBody: 'There are no upcoming events in the current calendar. Explore past events and check back for updates.', viewCalendar: 'View calendar', eventCount: 'events', eventSearch: 'Search by event, city or category', upcoming: 'Upcoming & ongoing', allEvents: 'All events', allCountries: 'All countries', noResults: 'No matching events.', past: 'Ended', officialSite: 'Official website',
  countries: { Belgium: 'Belgium', Germany: 'Germany', Netherlands: 'Netherlands', Italy: 'Italy', France: 'France', Spain: 'Spain', Portugal: 'Portugal' },
  types: { Anime: 'Anime', Comics: 'Comics', Gaming: 'Video games', 'Pop Culture': 'Pop culture' },
  resourcesTitle: 'Programme, tickets and information ↗', officialTitle: 'Official website and updates', officialDescription: 'Programme, exhibitors and maps when available.', tickets: 'Official tickets', ticketsDescription: 'Check the options on the organiser’s website.', assistance: 'Event information and support', assistanceDescription: 'Answers from the organisers to frequently asked questions.', externalNotice: 'External links open the organisers’ websites.', community: 'COSMORA community', communityDescription: 'Explore community posts. The official programme is available above.', independentNotice: 'Independent COSMORA guide, not affiliated with or endorsed by the organisers. Official stands have not been connected yet.',
  zoomIn: 'Zoom in', zoomOut: 'Zoom out', mapLabel: 'Map and stands', exploreLucca: 'Explore Lucca', nightMode: 'NIGHT MODE', mapHeading: 'The city at your fingertips', mapDescription: 'Explore the streets on a real map of Lucca.', openMap: 'Open night map', mapPrivacy: 'Opening the map shares your IP address and displayed area with OpenStreetMap. GPS stays off.', interactiveMap: 'Interactive map of Lucca', cityMap: 'City map · stands not connected', stopGps: 'Turn off GPS', whereAmI: 'Where am I', backToLucca: 'Back to Lucca', gpsPrivacy: 'GPS and privacy', gpsPrivacyBody: 'GPS starts only when you tap “Where am I”. COSMORA does not save your location. The map provider receives the displayed area. Tracking stops when you leave the page or put the app in the background. Accuracy may decrease indoors.', exhibitors: 'Exhibitors and stands', standPlaceholder: 'Stand name or number…', noStandSearch: 'Search unavailable: the catalogue is not connected yet.', waitingCatalog: 'Waiting for the authorised exhibitor catalogue.', locationOff: 'Location off', locationPaused: 'Location paused: enable it again whenever you want.', locationUnsupported: 'Location is not supported on this device.', locating: 'Finding your location…', locationActive: 'Location active · approximate accuracy', locationDenied: 'Permission denied. You can use the map without GPS.', locationUnavailableOutside: 'Location unavailable. Try again outdoors.', locationUnavailable: 'Location unavailable. Please try again.', tileError: 'Parts of the map are unavailable. Check your connection.', mapError: 'Unable to load the map. Reload the page to try again.',
};

type EventMessages = typeof en;
export const eventMessages: Record<Locale, EventMessages> = {
  en,
  it: {
    home: 'Home COSMORA', openCommunity: 'Apri community', inbox: 'Messaggi e ordini', searchLabel: 'Cerca in COSMORA', searchPlaceholder: 'Prodotti, eventi, persone…', search: 'Cerca', featured: 'Prossimo evento', ongoing: 'In corso', discover: 'Scopri l’evento', passions: 'Le tue passioni', listings: 'Tutti gli annunci', cosplay: 'Cosplay', comics: 'Manga e fumetti', figures: 'Action figure', cards: 'Carte collezionabili', gaming: 'Videogiochi', people: 'Persone e venditori', events: 'Eventi in Europa', eventsSubtitle: 'Fiere, festival e incontri', noUpcoming: 'Nuovi eventi in arrivo', noUpcomingBody: 'Non ci sono eventi futuri nel calendario attuale. Esplora quelli passati e torna per gli aggiornamenti.', viewCalendar: 'Apri il calendario', eventCount: 'eventi', eventSearch: 'Cerca evento, città o categoria', upcoming: 'Prossimi e in corso', allEvents: 'Tutti gli eventi', allCountries: 'Tutti i paesi', noResults: 'Nessun evento corrispondente.', past: 'Terminato', officialSite: 'Sito ufficiale',
    countries: { Belgium: 'Belgio', Germany: 'Germania', Netherlands: 'Paesi Bassi', Italy: 'Italia', France: 'Francia', Spain: 'Spagna', Portugal: 'Portogallo' },
    types: { Anime: 'Anime', Comics: 'Fumetti', Gaming: 'Videogiochi', 'Pop Culture': 'Cultura pop' },
    resourcesTitle: 'Programma, biglietti e informazioni ↗', officialTitle: 'Sito ufficiale e aggiornamenti', officialDescription: 'Programma, espositori e mappe quando disponibili.', tickets: 'Biglietti ufficiali', ticketsDescription: 'Consulta le opzioni sul sito dell’organizzatore.', assistance: 'Informazioni e assistenza evento', assistanceDescription: 'Le risposte degli organizzatori alle domande frequenti.', externalNotice: 'I collegamenti esterni aprono i siti degli organizzatori.', community: 'Community COSMORA', communityDescription: 'Esplora i post della community. Il programma ufficiale è disponibile qui sopra.', independentNotice: 'Guida indipendente di COSMORA, non affiliata né approvata dagli organizzatori. Nessuno stand ufficiale ancora collegato.',
    zoomIn: 'Ingrandisci', zoomOut: 'Riduci', mapLabel: 'Mappa e stand', exploreLucca: 'Esplora Lucca', nightMode: 'MODALITÀ NOTTURNA', mapHeading: 'La città, a portata di mano', mapDescription: 'Esplora le strade sulla mappa reale di Lucca.', openMap: 'Apri la mappa notturna', mapPrivacy: 'Aprendo la mappa, OpenStreetMap riceve IP e area visualizzata. Il GPS resta spento.', interactiveMap: 'Mappa interattiva di Lucca', cityMap: 'Mappa città · stand non collegati', stopGps: 'Spegni GPS', whereAmI: 'Dove sono', backToLucca: 'Torna a Lucca', gpsPrivacy: 'GPS e privacy', gpsPrivacyBody: 'Il GPS parte solo premendo “Dove sono”. COSMORA non salva la posizione. Il fornitore della mappa riceve l’area visualizzata. Il rilevamento si interrompe uscendo dalla pagina o passando in secondo piano. Nei padiglioni la precisione può diminuire.', exhibitors: 'Espositori e stand', standPlaceholder: 'Nome o numero dello stand…', noStandSearch: 'Ricerca non disponibile: catalogo non ancora collegato.', waitingCatalog: 'In attesa del catalogo autorizzato degli espositori.', locationOff: 'Posizione disattivata', locationPaused: 'Posizione sospesa: riattivala quando vuoi.', locationUnsupported: 'Posizione non supportata da questo dispositivo.', locating: 'Cerco la tua posizione…', locationActive: 'Posizione attiva · precisione circa', locationDenied: 'Permesso negato. Puoi usare la mappa senza GPS.', locationUnavailableOutside: 'Posizione non disponibile. Riprova all’aperto.', locationUnavailable: 'Posizione non disponibile. Riprova.', tileError: 'Alcune parti della mappa non sono disponibili. Controlla la connessione.', mapError: 'Impossibile caricare la mappa. Ricarica la pagina per riprovare.',
  },
  fr: {
    home: 'Accueil COSMORA', openCommunity: 'Ouvrir la communauté', inbox: 'Messages et commandes', searchLabel: 'Rechercher dans COSMORA', searchPlaceholder: 'Produits, événements, personnes…', search: 'Rechercher', featured: 'Prochain événement', ongoing: 'En cours', discover: 'Découvrir l’événement', passions: 'Vos passions', listings: 'Toutes les annonces', cosplay: 'Cosplay', comics: 'Mangas et BD', figures: 'Figurines', cards: 'Cartes à collectionner', gaming: 'Jeux vidéo', people: 'Membres et vendeurs', events: 'Événements en Europe', eventsSubtitle: 'Salons, festivals et rencontres', noUpcoming: 'De nouveaux événements arrivent', noUpcomingBody: 'Aucun événement à venir dans le calendrier actuel. Découvrez les événements passés et revenez pour les mises à jour.', viewCalendar: 'Voir le calendrier', eventCount: 'événements', eventSearch: 'Rechercher un événement, une ville ou une catégorie', upcoming: 'À venir et en cours', allEvents: 'Tous les événements', allCountries: 'Tous les pays', noResults: 'Aucun événement correspondant.', past: 'Terminé', officialSite: 'Site officiel',
    countries: { Belgium: 'Belgique', Germany: 'Allemagne', Netherlands: 'Pays-Bas', Italy: 'Italie', France: 'France', Spain: 'Espagne', Portugal: 'Portugal' },
    types: { Anime: 'Anime', Comics: 'BD', Gaming: 'Jeux vidéo', 'Pop Culture': 'Culture pop' },
    resourcesTitle: 'Programme, billets et informations ↗', officialTitle: 'Site officiel et actualités', officialDescription: 'Programme, exposants et plans dès leur disponibilité.', tickets: 'Billetterie officielle', ticketsDescription: 'Consultez les options sur le site de l’organisateur.', assistance: 'Informations et assistance', assistanceDescription: 'Les réponses des organisateurs aux questions fréquentes.', externalNotice: 'Les liens externes ouvrent les sites des organisateurs.', community: 'Communauté COSMORA', communityDescription: 'Découvrez les publications de la communauté. Le programme officiel est accessible ci-dessus.', independentNotice: 'Guide indépendant de COSMORA, sans affiliation ni approbation des organisateurs. Aucun stand officiel n’est encore connecté.',
    zoomIn: 'Zoom avant', zoomOut: 'Zoom arrière', mapLabel: 'Carte et stands', exploreLucca: 'Explorer Lucques', nightMode: 'MODE NUIT', mapHeading: 'La ville à portée de main', mapDescription: 'Explorez les rues sur la carte de Lucques.', openMap: 'Ouvrir la carte nocturne', mapPrivacy: 'En ouvrant la carte, OpenStreetMap reçoit votre adresse IP et la zone affichée. Le GPS reste désactivé.', interactiveMap: 'Carte interactive de Lucques', cityMap: 'Plan de la ville · stands non connectés', stopGps: 'Désactiver le GPS', whereAmI: 'Où suis-je', backToLucca: 'Retour à Lucques', gpsPrivacy: 'GPS et confidentialité', gpsPrivacyBody: 'Le GPS démarre uniquement lorsque vous appuyez sur « Où suis-je ». COSMORA n’enregistre pas votre position. Le fournisseur de carte reçoit la zone affichée. Le suivi s’arrête lorsque vous quittez la page ou passez l’app en arrière-plan. La précision peut diminuer à l’intérieur.', exhibitors: 'Exposants et stands', standPlaceholder: 'Nom ou numéro du stand…', noStandSearch: 'Recherche indisponible : le catalogue n’est pas encore connecté.', waitingCatalog: 'En attente du catalogue autorisé des exposants.', locationOff: 'Localisation désactivée', locationPaused: 'Localisation suspendue : réactivez-la quand vous le souhaitez.', locationUnsupported: 'La localisation n’est pas prise en charge sur cet appareil.', locating: 'Recherche de votre position…', locationActive: 'Localisation active · précision approximative', locationDenied: 'Autorisation refusée. Vous pouvez utiliser la carte sans GPS.', locationUnavailableOutside: 'Position indisponible. Réessayez à l’extérieur.', locationUnavailable: 'Position indisponible. Veuillez réessayer.', tileError: 'Certaines parties de la carte sont indisponibles. Vérifiez votre connexion.', mapError: 'Impossible de charger la carte. Rechargez la page pour réessayer.',
  },
  de: {
    home: 'COSMORA Startseite', openCommunity: 'Community öffnen', inbox: 'Nachrichten und Bestellungen', searchLabel: 'COSMORA durchsuchen', searchPlaceholder: 'Produkte, Events, Personen…', search: 'Suchen', featured: 'Nächstes Event', ongoing: 'Findet gerade statt', discover: 'Event entdecken', passions: 'Deine Interessen', listings: 'Alle Angebote', cosplay: 'Cosplay', comics: 'Manga und Comics', figures: 'Actionfiguren', cards: 'Sammelkarten', gaming: 'Videospiele', people: 'Mitglieder & Verkäufer', events: 'Events in Europa', eventsSubtitle: 'Messen, Festivals und Treffen', noUpcoming: 'Neue Events folgen bald', noUpcomingBody: 'Im aktuellen Kalender stehen keine kommenden Events. Entdecke vergangene Events und schaue bald wieder vorbei.', viewCalendar: 'Kalender öffnen', eventCount: 'Events', eventSearch: 'Event, Stadt oder Kategorie suchen', upcoming: 'Aktuell und demnächst', allEvents: 'Alle Events', allCountries: 'Alle Länder', noResults: 'Keine passenden Events.', past: 'Beendet', officialSite: 'Offizielle Website',
    countries: { Belgium: 'Belgien', Germany: 'Deutschland', Netherlands: 'Niederlande', Italy: 'Italien', France: 'Frankreich', Spain: 'Spanien', Portugal: 'Portugal' },
    types: { Anime: 'Anime', Comics: 'Comics', Gaming: 'Videospiele', 'Pop Culture': 'Popkultur' },
    resourcesTitle: 'Programm, Tickets und Informationen ↗', officialTitle: 'Offizielle Website und Neuigkeiten', officialDescription: 'Programm, Aussteller und Pläne, sobald verfügbar.', tickets: 'Offizielle Tickets', ticketsDescription: 'Entdecke die Optionen auf der Website des Veranstalters.', assistance: 'Informationen und Hilfe zum Event', assistanceDescription: 'Antworten der Veranstalter auf häufige Fragen.', externalNotice: 'Externe Links öffnen die Websites der Veranstalter.', community: 'COSMORA Community', communityDescription: 'Entdecke Beiträge der Community. Das offizielle Programm findest du oben.', independentNotice: 'Unabhängiger COSMORA-Guide, ohne Verbindung zu oder Genehmigung durch die Veranstalter. Offizielle Stände sind noch nicht eingebunden.',
    zoomIn: 'Vergrößern', zoomOut: 'Verkleinern', mapLabel: 'Karte und Stände', exploreLucca: 'Lucca erkunden', nightMode: 'NACHTMODUS', mapHeading: 'Die Stadt in deiner Hand', mapDescription: 'Erkunde die Straßen auf einer echten Karte von Lucca.', openMap: 'Nachtkarte öffnen', mapPrivacy: 'Beim Öffnen der Karte erhält OpenStreetMap deine IP-Adresse und den angezeigten Bereich. GPS bleibt ausgeschaltet.', interactiveMap: 'Interaktive Karte von Lucca', cityMap: 'Stadtplan · Stände nicht eingebunden', stopGps: 'GPS ausschalten', whereAmI: 'Wo bin ich', backToLucca: 'Zurück nach Lucca', gpsPrivacy: 'GPS und Datenschutz', gpsPrivacyBody: 'GPS startet erst, wenn du auf „Wo bin ich“ tippst. COSMORA speichert deinen Standort nicht. Der Kartenanbieter erhält den angezeigten Bereich. Die Ortung endet, sobald du die Seite verlässt oder die App in den Hintergrund wechselst. In Gebäuden kann die Genauigkeit abnehmen.', exhibitors: 'Aussteller und Stände', standPlaceholder: 'Name oder Nummer des Stands…', noStandSearch: 'Suche nicht verfügbar: Der Katalog ist noch nicht eingebunden.', waitingCatalog: 'Der freigegebene Ausstellerkatalog ist noch nicht verfügbar.', locationOff: 'Ortung ausgeschaltet', locationPaused: 'Ortung pausiert: Du kannst sie jederzeit wieder einschalten.', locationUnsupported: 'Dieses Gerät unterstützt keine Ortung.', locating: 'Dein Standort wird gesucht…', locationActive: 'Ortung aktiv · ungefähre Genauigkeit', locationDenied: 'Zugriff verweigert. Du kannst die Karte ohne GPS verwenden.', locationUnavailableOutside: 'Standort nicht verfügbar. Versuche es im Freien erneut.', locationUnavailable: 'Standort nicht verfügbar. Bitte versuche es erneut.', tileError: 'Teile der Karte sind nicht verfügbar. Prüfe deine Verbindung.', mapError: 'Die Karte konnte nicht geladen werden. Lade die Seite erneut.',
  },
  es: {
    home: 'Inicio de COSMORA', openCommunity: 'Abrir comunidad', inbox: 'Mensajes y pedidos', searchLabel: 'Buscar en COSMORA', searchPlaceholder: 'Productos, eventos, personas…', search: 'Buscar', featured: 'Próximo evento', ongoing: 'En curso', discover: 'Descubrir el evento', passions: 'Tus aficiones', listings: 'Todos los anuncios', cosplay: 'Cosplay', comics: 'Manga y cómics', figures: 'Figuras de acción', cards: 'Cartas coleccionables', gaming: 'Videojuegos', people: 'Personas y vendedores', events: 'Eventos en Europa', eventsSubtitle: 'Ferias, festivales y encuentros', noUpcoming: 'Próximamente, nuevos eventos', noUpcomingBody: 'No hay próximos eventos en el calendario actual. Explora los eventos pasados y vuelve para ver las novedades.', viewCalendar: 'Ver calendario', eventCount: 'eventos', eventSearch: 'Buscar evento, ciudad o categoría', upcoming: 'Próximos y en curso', allEvents: 'Todos los eventos', allCountries: 'Todos los países', noResults: 'No se encontraron eventos.', past: 'Finalizado', officialSite: 'Web oficial',
    countries: { Belgium: 'Bélgica', Germany: 'Alemania', Netherlands: 'Países Bajos', Italy: 'Italia', France: 'Francia', Spain: 'España', Portugal: 'Portugal' },
    types: { Anime: 'Anime', Comics: 'Cómics', Gaming: 'Videojuegos', 'Pop Culture': 'Cultura pop' },
    resourcesTitle: 'Programa, entradas e información ↗', officialTitle: 'Web oficial y novedades', officialDescription: 'Programa, expositores y mapas cuando estén disponibles.', tickets: 'Entradas oficiales', ticketsDescription: 'Consulta las opciones en la web del organizador.', assistance: 'Información y asistencia del evento', assistanceDescription: 'Respuestas de los organizadores a las preguntas frecuentes.', externalNotice: 'Los enlaces externos abren las webs de los organizadores.', community: 'Comunidad COSMORA', communityDescription: 'Explora las publicaciones de la comunidad. El programa oficial está disponible arriba.', independentNotice: 'Guía independiente de COSMORA, sin afiliación ni aprobación de los organizadores. Los stands oficiales aún no están conectados.',
    zoomIn: 'Acercar', zoomOut: 'Alejar', mapLabel: 'Mapa y stands', exploreLucca: 'Explorar Lucca', nightMode: 'MODO NOCTURNO', mapHeading: 'La ciudad, al alcance de tu mano', mapDescription: 'Explora las calles en el mapa real de Lucca.', openMap: 'Abrir el mapa nocturno', mapPrivacy: 'Al abrir el mapa, OpenStreetMap recibe tu IP y la zona mostrada. El GPS sigue apagado.', interactiveMap: 'Mapa interactivo de Lucca', cityMap: 'Mapa de la ciudad · stands sin conectar', stopGps: 'Apagar GPS', whereAmI: 'Dónde estoy', backToLucca: 'Volver a Lucca', gpsPrivacy: 'GPS y privacidad', gpsPrivacyBody: 'El GPS solo se activa al pulsar «Dónde estoy». COSMORA no guarda tu ubicación. El proveedor del mapa recibe la zona mostrada. El seguimiento se detiene al salir de la página o pasar la app a segundo plano. La precisión puede disminuir en interiores.', exhibitors: 'Expositores y stands', standPlaceholder: 'Nombre o número del stand…', noStandSearch: 'Búsqueda no disponible: el catálogo aún no está conectado.', waitingCatalog: 'A la espera del catálogo autorizado de expositores.', locationOff: 'Ubicación desactivada', locationPaused: 'Ubicación en pausa: actívala de nuevo cuando quieras.', locationUnsupported: 'Este dispositivo no admite la ubicación.', locating: 'Buscando tu ubicación…', locationActive: 'Ubicación activa · precisión aproximada', locationDenied: 'Permiso denegado. Puedes usar el mapa sin GPS.', locationUnavailableOutside: 'Ubicación no disponible. Inténtalo al aire libre.', locationUnavailable: 'Ubicación no disponible. Inténtalo de nuevo.', tileError: 'Algunas partes del mapa no están disponibles. Comprueba la conexión.', mapError: 'No se pudo cargar el mapa. Recarga la página para volver a intentarlo.',
  },
};

export function eventCountry(country: string, locale: Locale): string {
  return eventMessages[locale].countries[country as keyof EventMessages['countries']] ?? country;
}
