import type { Locale } from './config';

const italianSections = [
  ['Chi gestisce i tuoi dati', 'Il titolare del trattamento è Andrea Gadducci, titolare della ditta individuale Kreluna Software. Puoi contattarci a info@kreluna.it indicando nell’oggetto [COSMORA] Privacy. Questa informativa riguarda il sito e l’app COSMORA.'],
  ['Account e profilo', 'Trattiamo email, identificativo dell’account, credenziali gestite dal servizio di autenticazione, nome pubblico e paese inseriti nel profilo. Se accedi con Apple o Google, riceviamo i dati che il servizio di accesso rende disponibili, come email, nome e immagine del profilo. Non riceviamo la password del tuo account Apple o Google. Questi dati servono a creare e mantenere l’account e a fornire le funzioni richieste, sulla base dell’esecuzione del servizio (art. 6.1.b GDPR). I campi obbligatori sono necessari per la relativa funzione; senza di essi potresti non poterla utilizzare.'],
  ['Community, annunci e messaggi', 'Conserviamo le foto e i video che carichi, le descrizioni dei post e degli annunci, i messaggi, le preferenze salvate, i voti e le partecipazioni alle crew per consentirti di usare queste funzioni. Nome pubblico, paese, post e annunci possono essere visibili anche a visitatori non autenticati. I messaggi sono destinati ai partecipanti alla conversazione; non sono post pubblici. Non inserire dati sensibili o informazioni di altre persone senza una base legittima. I contenuti resi pubblici possono essere copiati da altri: la cancellazione da COSMORA non rimuove automaticamente copie esterne.'],
  ['Venditori e ordini', 'Per il profilo venditore trattiamo i contatti, il paese e i dati commerciali, di fatturazione e consegna che inserisci. Ai negozi vengono richiesti anche dati aziendali e condizioni di vendita. Le funzionalità relative agli ordini registrano i partecipanti, i prodotti, gli importi, gli stati e gli identificativi di pagamento. Nella versione attuale l’integrazione Stripe è in modalità di prova: non rappresenta un servizio di incasso reale né un deposito a garanzia. Quando utilizzi il collegamento Stripe, i dati necessari al conto e alla sessione di pagamento sono trasmessi a Stripe. Non inserire carte o documenti reali nei flussi di prova.'],
  ['Foto, posizione e funzioni facoltative', 'Accediamo ai file che scegli di caricare, non pubblichiamo automaticamente l’intera libreria Foto. Il modulo di rimozione dello sfondo della sezione vendita elabora l’immagine sul dispositivo dopo il download facoltativo del modello; pubblicare successivamente la foto è un’operazione distinta. La mappa OpenStreetMap si carica quando la apri e comunica al fornitore IP e area visualizzata. La posizione GPS viene utilizzata sul dispositivo solo quando la attivi, per mostrare il punto sulla mappa; il componente non salva le coordinate nel database COSMORA. Le richieste cartografiche possono comunque rivelare l’area visualizzata. Puoi revocare i permessi dalle impostazioni del dispositivo e usare le altre funzioni senza GPS.'],
  ['Assistenza e sicurezza', 'Trattiamo i messaggi inviati all’assistenza, le segnalazioni e i blocchi per rispondere alle richieste e contrastare abusi. I controlli automatici sul testo possono sospendere la pubblicazione di un contenuto in attesa di verifica; puoi chiedere un riesame all’assistenza. Le operazioni di sicurezza e moderazione si basano sul legittimo interesse a proteggere utenti e servizio (art. 6.1.f GDPR), fatto salvo il diritto di opposizione. Eventuali adempimenti obbligatori si basano sull’art. 6.1.c GDPR. Non inviare password, codici temporanei o dati completi di carte all’assistenza.'],
  ['Fornitori e dati tecnici', 'Utilizziamo Supabase per autenticazione, database e file, Sites e l’infrastruttura Cloudflare per erogare il sito, e Aruba per la posta di assistenza. Apple, Google, Stripe e OpenStreetMap intervengono quando utilizzi le rispettive funzioni. Le infrastrutture possono trattare IP, richieste e registri tecnici necessari al funzionamento e alla sicurezza. Sul dispositivo vengono conservati dati di sessione e preferenze tecniche, come la lingua. Non utilizziamo questi dati per pubblicità comportamentale. I servizi esterni possono operare in più paesi: non garantiamo che ogni trattamento avvenga esclusivamente nello Spazio economico europeo. Puoi richiedere informazioni sui destinatari e sulle garanzie applicabili a info@kreluna.it.'],
  ['Conservazione e cancellazione', 'Account e contenuti restano conservati finché mantieni l’account o ne richiedi la cancellazione, salvo necessità di gestione di operazioni, contestazioni o obblighi legali. La durata dei dati di assistenza e sicurezza dipende dalla gestione della richiesta o dell’incidente e dalla necessità di tutelare diritti; i log e le copie di backup dipendono anche dal servizio infrastrutturale utilizzato. Non promettiamo cancellazione istantanea da ogni backup. Puoi eliminare l’account dalla funzione dedicata: il flusso rimuove account, contenuti associati e file. Se risultano operazioni reali da gestire, la procedura richiede di contattare l’assistenza. In caso di errore nella cancellazione, scrivici per completare la richiesta.'],
  ['I tuoi diritti', 'Nei casi previsti dal GDPR puoi chiedere accesso, rettifica, cancellazione, limitazione e portabilità dei dati, e opporti ai trattamenti basati sul legittimo interesse. Quando un trattamento si basa sul consenso, puoi revocarlo senza pregiudicare la liceità del trattamento precedente. Scrivi a info@kreluna.it: potremmo chiederti le informazioni strettamente necessarie a verificare la tua identità. Hai diritto di presentare reclamo al Garante per la protezione dei dati personali o all’autorità competente nel tuo paese.'],
  ['Aggiornamenti', 'Aggiorneremo questa informativa se cambiano le funzioni o il trattamento dei dati. In particolare, l’eventuale attivazione di pagamenti reali richiederà informazioni aggiornate prima del loro utilizzo. Ultimo aggiornamento: 7 settembre 2026.'],
];

type PrivacyMessages = { title: string; heading: string; contact: string; deleteAccount: string; authority: string; sections: string[][] };

export const privacyMessages: Record<Locale, PrivacyMessages> = {
  it: { title: 'Privacy', heading: 'Informativa sulla privacy', contact: 'Contatta il titolare per la privacy', deleteAccount: 'Elimina il tuo account', authority: 'Garante per la protezione dei dati personali', sections: italianSections },
  en: {
    title: 'Privacy', heading: 'Privacy notice', contact: 'Contact the data controller about privacy', deleteAccount: 'Delete your account', authority: 'Italian Data Protection Authority',
    sections: [
      ['Who manages your data', 'The data controller is Andrea Gadducci, owner of the sole proprietorship Kreluna Software. You can contact us at info@kreluna.it with [COSMORA] Privacy in the subject line. This notice covers the COSMORA website and app.'],
      ['Account and profile', 'We process your email address, account identifier, credentials managed by the authentication service, and the public name and country entered in your profile. If you sign in with Apple or Google, we receive the data made available by that sign-in service, such as your email address, name and profile picture. We do not receive your Apple or Google account password. These data are used to create and maintain your account and provide the requested features, on the basis of performing the service (Article 6(1)(b) GDPR). Required fields are necessary for the relevant feature; without them, you may be unable to use it.'],
      ['Community, listings and messages', 'We store the photos and videos you upload, post and listing descriptions, messages, saved preferences, votes and crew memberships so that you can use these features. Your public name, country, posts and listings may also be visible to visitors who are not signed in. Messages are intended for the conversation participants; they are not public posts. Do not enter sensitive data or information about other people without a legitimate basis. Publicly shared content may be copied by others: deleting it from COSMORA does not automatically remove external copies.'],
      ['Sellers and orders', 'For your seller profile, we process the contact details, country, and commercial, billing and delivery information you enter. Shops are also asked for business details and terms of sale. Order features record the participants, products, amounts, statuses and payment identifiers. In the current version, the Stripe integration is in test mode: it is neither a real payment collection service nor an escrow service. When you use the Stripe connection, the data necessary for the account and payment session are transmitted to Stripe. Do not enter real card or document details in test flows.'],
      ['Photos, location and optional features', 'We access the files you choose to upload; we do not automatically publish your entire photo library. The background removal module in the selling section processes the image on your device after the optional model download; subsequently publishing the photo is a separate action. The OpenStreetMap map loads when you open it and communicates your IP address and displayed area to the provider. GPS location is used on your device only when you enable it, to show your position on the map; the component does not save coordinates in the COSMORA database. Map requests may nevertheless reveal the displayed area. You can revoke permissions in your device settings and use other features without GPS.'],
      ['Support and security', 'We process messages sent to support, reports and blocks to respond to requests and combat abuse. Automatic text checks may suspend the publication of content pending review; you can ask support for a review. Security and moderation operations are based on the legitimate interest in protecting users and the service (Article 6(1)(f) GDPR), subject to the right to object. Any mandatory compliance obligations are based on Article 6(1)(c) GDPR. Do not send passwords, temporary codes or full card details to support.'],
      ['Providers and technical data', 'We use Supabase for authentication, databases and files, Sites and Cloudflare infrastructure to serve the website, and Aruba for support email. Apple, Google, Stripe and OpenStreetMap are involved when you use their respective features. Infrastructure providers may process IP addresses, requests and technical logs necessary for operation and security. Session data and technical preferences, such as language, are stored on your device. We do not use these data for behavioural advertising. External services may operate in multiple countries: we do not guarantee that all processing takes place exclusively within the European Economic Area. You can request information about recipients and applicable safeguards at info@kreluna.it.'],
      ['Retention and deletion', 'Your account and content are retained while you maintain your account or until you request deletion, unless they are needed to manage transactions, disputes or legal obligations. The retention period for support and security data depends on the handling of the request or incident and the need to protect rights; logs and backups also depend on the infrastructure service used. We do not promise instant deletion from every backup. You can delete your account using the dedicated feature: the process removes the account, associated content and files. If there are real transactions to handle, the process requires you to contact support. If deletion fails, write to us to complete your request.'],
      ['Your rights', 'Where provided for by the GDPR, you may request access to, rectification, deletion, restriction and portability of your data, and object to processing based on legitimate interests. Where processing is based on consent, you may withdraw it without affecting the lawfulness of earlier processing. Write to info@kreluna.it: we may ask for the information strictly necessary to verify your identity. You have the right to lodge a complaint with the Italian Data Protection Authority or the competent authority in your country.'],
      ['Updates', 'We will update this notice if features or data processing change. In particular, any activation of real payments will require updated information before they are used. Last updated: 7 September 2026.'],
    ],
  },
  fr: {
    title: 'Confidentialité', heading: 'Politique de confidentialité', contact: 'Contacter le responsable du traitement', deleteAccount: 'Supprimer votre compte', authority: 'Autorité italienne de protection des données',
    sections: [
      ['Qui gère vos données', 'Le responsable du traitement est Andrea Gadducci, propriétaire de l’entreprise individuelle Kreluna Software. Vous pouvez nous contacter à info@kreluna.it en indiquant [COSMORA] Privacy dans l’objet. Cette politique concerne le site et l’application COSMORA.'],
      ['Compte et profil', 'Nous traitons votre adresse e-mail, l’identifiant de votre compte, les identifiants gérés par le service d’authentification, ainsi que le nom public et le pays renseignés dans votre profil. Si vous vous connectez avec Apple ou Google, nous recevons les données mises à disposition par le service de connexion, comme l’adresse e-mail, le nom et la photo de profil. Nous ne recevons pas le mot de passe de votre compte Apple ou Google. Ces données servent à créer et maintenir votre compte et à fournir les fonctionnalités demandées, sur la base de l’exécution du service (article 6, paragraphe 1, point b du RGPD). Les champs obligatoires sont nécessaires à la fonctionnalité concernée ; sans eux, vous pourriez ne pas pouvoir l’utiliser.'],
      ['Communauté, annonces et messages', 'Nous conservons les photos et vidéos que vous importez, les descriptions des publications et annonces, les messages, les préférences enregistrées, les votes et les adhésions aux crews afin de vous permettre d’utiliser ces fonctionnalités. Le nom public, le pays, les publications et les annonces peuvent aussi être visibles par des visiteurs non connectés. Les messages sont destinés aux participants à la conversation ; ce ne sont pas des publications publiques. Ne saisissez pas de données sensibles ou d’informations concernant d’autres personnes sans base légitime. Les contenus rendus publics peuvent être copiés par d’autres : leur suppression de COSMORA ne supprime pas automatiquement les copies externes.'],
      ['Vendeurs et commandes', 'Pour le profil vendeur, nous traitons les coordonnées, le pays et les données commerciales, de facturation et de livraison que vous renseignez. Les boutiques doivent également fournir des informations sur leur entreprise et leurs conditions de vente. Les fonctionnalités de commande enregistrent les participants, les produits, les montants, les statuts et les identifiants de paiement. Dans la version actuelle, l’intégration Stripe est en mode test : elle ne constitue ni un service réel d’encaissement ni un dépôt de garantie. Lorsque vous utilisez la connexion Stripe, les données nécessaires au compte et à la session de paiement sont transmises à Stripe. Ne saisissez pas de véritables données de carte ou de document dans les parcours de test.'],
      ['Photos, localisation et fonctionnalités facultatives', 'Nous accédons aux fichiers que vous choisissez d’importer ; nous ne publions pas automatiquement l’ensemble de votre photothèque. Le module de suppression de l’arrière-plan de la section vente traite l’image sur votre appareil après le téléchargement facultatif du modèle ; publier ensuite la photo est une opération distincte. La carte OpenStreetMap se charge lorsque vous l’ouvrez et transmet au fournisseur votre adresse IP et la zone affichée. La position GPS est utilisée sur votre appareil uniquement lorsque vous l’activez, pour afficher votre position sur la carte ; le composant n’enregistre pas les coordonnées dans la base de données COSMORA. Les requêtes cartographiques peuvent toutefois révéler la zone affichée. Vous pouvez révoquer les autorisations dans les paramètres de votre appareil et utiliser les autres fonctionnalités sans GPS.'],
      ['Assistance et sécurité', 'Nous traitons les messages envoyés à l’assistance, les signalements et les blocages pour répondre aux demandes et lutter contre les abus. Les contrôles automatiques du texte peuvent suspendre la publication d’un contenu dans l’attente d’une vérification ; vous pouvez demander un réexamen à l’assistance. Les opérations de sécurité et de modération reposent sur l’intérêt légitime à protéger les utilisateurs et le service (article 6, paragraphe 1, point f du RGPD), sous réserve du droit d’opposition. Les éventuelles obligations légales reposent sur l’article 6, paragraphe 1, point c du RGPD. N’envoyez pas de mots de passe, de codes temporaires ou de données complètes de carte à l’assistance.'],
      ['Prestataires et données techniques', 'Nous utilisons Supabase pour l’authentification, la base de données et les fichiers, Sites et l’infrastructure Cloudflare pour fournir le site, et Aruba pour les e-mails d’assistance. Apple, Google, Stripe et OpenStreetMap interviennent lorsque vous utilisez leurs fonctionnalités respectives. Les infrastructures peuvent traiter les adresses IP, les requêtes et les journaux techniques nécessaires au fonctionnement et à la sécurité. Des données de session et des préférences techniques, comme la langue, sont conservées sur votre appareil. Nous n’utilisons pas ces données pour la publicité comportementale. Les services externes peuvent opérer dans plusieurs pays : nous ne garantissons pas que tous les traitements se déroulent exclusivement dans l’Espace économique européen. Vous pouvez demander des informations sur les destinataires et les garanties applicables à info@kreluna.it.'],
      ['Conservation et suppression', 'Le compte et les contenus sont conservés tant que vous maintenez votre compte ou jusqu’à votre demande de suppression, sauf nécessité de gérer des opérations, des litiges ou des obligations légales. La durée de conservation des données d’assistance et de sécurité dépend du traitement de la demande ou de l’incident et de la nécessité de protéger des droits ; les journaux et les sauvegardes dépendent également du service d’infrastructure utilisé. Nous ne promettons pas une suppression instantanée de chaque sauvegarde. Vous pouvez supprimer votre compte depuis la fonctionnalité dédiée : la procédure supprime le compte, les contenus associés et les fichiers. Si des opérations réelles restent à gérer, la procédure vous demande de contacter l’assistance. En cas d’erreur lors de la suppression, écrivez-nous pour finaliser votre demande.'],
      ['Vos droits', 'Dans les cas prévus par le RGPD, vous pouvez demander l’accès, la rectification, la suppression, la limitation et la portabilité des données, ainsi que vous opposer aux traitements fondés sur l’intérêt légitime. Lorsqu’un traitement repose sur le consentement, vous pouvez le retirer sans porter atteinte à la licéité du traitement antérieur. Écrivez à info@kreluna.it : nous pourrons vous demander les informations strictement nécessaires pour vérifier votre identité. Vous avez le droit de déposer une réclamation auprès de l’Autorité italienne de protection des données ou de l’autorité compétente dans votre pays.'],
      ['Mises à jour', 'Nous mettrons à jour cette politique si les fonctionnalités ou les traitements de données évoluent. En particulier, l’éventuelle activation de paiements réels nécessitera des informations actualisées avant leur utilisation. Dernière mise à jour : 7 septembre 2026.'],
    ],
  },
  de: {
    title: 'Datenschutz', heading: 'Datenschutzhinweise', contact: 'Verantwortlichen zum Datenschutz kontaktieren', deleteAccount: 'Dein Konto löschen', authority: 'Italienische Datenschutzbehörde',
    sections: [
      ['Wer deine Daten verwaltet', 'Verantwortlicher für die Verarbeitung ist Andrea Gadducci, Inhaber des Einzelunternehmens Kreluna Software. Du erreichst uns unter info@kreluna.it mit dem Betreff [COSMORA] Privacy. Diese Hinweise gelten für die Website und die App COSMORA.'],
      ['Konto und Profil', 'Wir verarbeiten deine E-Mail-Adresse, die Kontokennung, vom Authentifizierungsdienst verwaltete Zugangsdaten sowie den öffentlichen Namen und das im Profil angegebene Land. Wenn du dich mit Apple oder Google anmeldest, erhalten wir die vom jeweiligen Anmeldedienst bereitgestellten Daten, etwa E-Mail-Adresse, Name und Profilbild. Das Passwort deines Apple- oder Google-Kontos erhalten wir nicht. Diese Daten dienen dazu, dein Konto zu erstellen und zu führen sowie die angeforderten Funktionen bereitzustellen, auf Grundlage der Erfüllung des Dienstes (Art. 6 Abs. 1 Buchst. b DSGVO). Pflichtfelder sind für die jeweilige Funktion erforderlich; ohne sie kannst du diese möglicherweise nicht nutzen.'],
      ['Community, Angebote und Nachrichten', 'Wir speichern die von dir hochgeladenen Fotos und Videos, die Beschreibungen von Beiträgen und Angeboten, Nachrichten, gespeicherte Einstellungen, Abstimmungen und Crew-Mitgliedschaften, damit du diese Funktionen nutzen kannst. Öffentlicher Name, Land, Beiträge und Angebote können auch für nicht angemeldete Besucher sichtbar sein. Nachrichten sind für die Teilnehmer der Unterhaltung bestimmt; sie sind keine öffentlichen Beiträge. Gib keine sensiblen Daten oder Informationen über andere Personen ohne rechtmäßige Grundlage ein. Öffentlich geteilte Inhalte können von anderen kopiert werden: Das Löschen bei COSMORA entfernt externe Kopien nicht automatisch.'],
      ['Verkäufer und Bestellungen', 'Für dein Verkäuferprofil verarbeiten wir die von dir angegebenen Kontaktdaten, das Land sowie Geschäfts-, Rechnungs- und Lieferdaten. Geschäfte werden außerdem nach Unternehmensdaten und Verkaufsbedingungen gefragt. Bestellfunktionen erfassen die Beteiligten, Produkte, Beträge, Status und Zahlungskennungen. In der aktuellen Version läuft die Stripe-Integration im Testmodus: Sie stellt weder einen echten Zahlungsdienst noch einen Treuhandservice dar. Wenn du die Stripe-Verbindung nutzt, werden die für das Konto und die Zahlungssitzung erforderlichen Daten an Stripe übermittelt. Gib in Testabläufen keine echten Karten- oder Dokumentdaten ein.'],
      ['Fotos, Standort und optionale Funktionen', 'Wir greifen auf die Dateien zu, die du zum Hochladen auswählst; wir veröffentlichen nicht automatisch deine gesamte Fotomediathek. Das Modul zur Hintergrundentfernung im Verkaufsbereich verarbeitet das Bild nach dem optionalen Herunterladen des Modells auf deinem Gerät; das spätere Veröffentlichen des Fotos ist ein eigener Vorgang. Die OpenStreetMap-Karte wird beim Öffnen geladen und übermittelt dem Anbieter deine IP-Adresse und den angezeigten Bereich. Der GPS-Standort wird auf deinem Gerät nur verwendet, wenn du ihn aktivierst, um deine Position auf der Karte anzuzeigen; die Komponente speichert die Koordinaten nicht in der COSMORA-Datenbank. Kartenanfragen können dennoch den angezeigten Bereich offenlegen. Du kannst Berechtigungen in den Geräteeinstellungen widerrufen und die anderen Funktionen ohne GPS nutzen.'],
      ['Support und Sicherheit', 'Wir verarbeiten an den Support gesendete Nachrichten, Meldungen und Blockierungen, um Anfragen zu beantworten und Missbrauch zu bekämpfen. Automatische Textprüfungen können die Veröffentlichung von Inhalten bis zur Prüfung aussetzen; du kannst den Support um eine erneute Prüfung bitten. Sicherheits- und Moderationsmaßnahmen beruhen auf dem berechtigten Interesse am Schutz der Nutzer und des Dienstes (Art. 6 Abs. 1 Buchst. f DSGVO), vorbehaltlich des Widerspruchsrechts. Etwaige gesetzliche Pflichten beruhen auf Art. 6 Abs. 1 Buchst. c DSGVO. Sende dem Support keine Passwörter, Einmalcodes oder vollständigen Kartendaten.'],
      ['Dienstleister und technische Daten', 'Wir nutzen Supabase für Authentifizierung, Datenbank und Dateien, Sites und die Cloudflare-Infrastruktur für die Bereitstellung der Website sowie Aruba für Support-E-Mails. Apple, Google, Stripe und OpenStreetMap werden einbezogen, wenn du die jeweiligen Funktionen nutzt. Die Infrastruktur kann IP-Adressen, Anfragen und technische Protokolle verarbeiten, die für Betrieb und Sicherheit erforderlich sind. Auf deinem Gerät werden Sitzungsdaten und technische Einstellungen wie die Sprache gespeichert. Wir verwenden diese Daten nicht für verhaltensbasierte Werbung. Externe Dienste können in mehreren Ländern tätig sein: Wir garantieren nicht, dass jede Verarbeitung ausschließlich im Europäischen Wirtschaftsraum stattfindet. Informationen zu Empfängern und geltenden Garantien kannst du unter info@kreluna.it anfordern.'],
      ['Speicherung und Löschung', 'Konto und Inhalte bleiben gespeichert, solange du dein Konto führst oder bis du die Löschung beantragst, sofern sie nicht zur Abwicklung von Vorgängen, Streitfällen oder gesetzlichen Pflichten benötigt werden. Die Speicherdauer von Support- und Sicherheitsdaten hängt von der Bearbeitung der Anfrage oder des Vorfalls und dem Schutz von Rechten ab; Protokolle und Sicherungskopien hängen auch vom verwendeten Infrastrukturdienst ab. Wir versprechen keine sofortige Löschung aus jeder Sicherungskopie. Du kannst dein Konto über die dafür vorgesehene Funktion löschen: Der Ablauf entfernt das Konto, zugehörige Inhalte und Dateien. Wenn echte Vorgänge noch zu bearbeiten sind, wirst du aufgefordert, den Support zu kontaktieren. Bei einem Löschfehler schreibe uns, damit wir deinen Antrag abschließen können.'],
      ['Deine Rechte', 'In den von der DSGVO vorgesehenen Fällen kannst du Auskunft, Berichtigung, Löschung, Einschränkung und Übertragbarkeit deiner Daten verlangen und Verarbeitungen auf Grundlage berechtigter Interessen widersprechen. Beruht eine Verarbeitung auf deiner Einwilligung, kannst du diese widerrufen, ohne die Rechtmäßigkeit der vorherigen Verarbeitung zu beeinträchtigen. Schreibe an info@kreluna.it: Wir können die Informationen anfordern, die zur Überprüfung deiner Identität unbedingt erforderlich sind. Du hast das Recht, dich bei der italienischen Datenschutzbehörde oder der zuständigen Behörde in deinem Land zu beschweren.'],
      ['Aktualisierungen', 'Wir aktualisieren diese Hinweise, wenn sich Funktionen oder die Datenverarbeitung ändern. Insbesondere erfordert eine mögliche Aktivierung echter Zahlungen aktualisierte Informationen vor deren Nutzung. Zuletzt aktualisiert: 7. September 2026.'],
    ],
  },
  es: {
    title: 'Privacidad', heading: 'Aviso de privacidad', contact: 'Contactar con el responsable de privacidad', deleteAccount: 'Eliminar tu cuenta', authority: 'Autoridad italiana de protección de datos',
    sections: [
      ['Quién gestiona tus datos', 'El responsable del tratamiento es Andrea Gadducci, titular de la empresa individual Kreluna Software. Puedes contactar con nosotros en info@kreluna.it indicando [COSMORA] Privacy en el asunto. Este aviso se aplica al sitio web y a la app COSMORA.'],
      ['Cuenta y perfil', 'Tratamos el correo electrónico, el identificador de la cuenta, las credenciales gestionadas por el servicio de autenticación, el nombre público y el país introducidos en el perfil. Si accedes con Apple o Google, recibimos los datos que el servicio de acceso facilita, como correo electrónico, nombre e imagen de perfil. No recibimos la contraseña de tu cuenta de Apple o Google. Estos datos sirven para crear y mantener la cuenta y proporcionar las funciones solicitadas, sobre la base de la ejecución del servicio (artículo 6.1.b del RGPD). Los campos obligatorios son necesarios para la función correspondiente; sin ellos, podrías no poder utilizarla.'],
      ['Comunidad, anuncios y mensajes', 'Conservamos las fotos y los vídeos que subes, las descripciones de las publicaciones y los anuncios, los mensajes, las preferencias guardadas, los votos y las pertenencias a crews para que puedas utilizar estas funciones. El nombre público, el país, las publicaciones y los anuncios también pueden ser visibles para visitantes que no hayan iniciado sesión. Los mensajes están destinados a los participantes de la conversación; no son publicaciones públicas. No introduzcas datos sensibles ni información de otras personas sin una base legítima. Los contenidos públicos pueden ser copiados por otros: su eliminación de COSMORA no elimina automáticamente las copias externas.'],
      ['Vendedores y pedidos', 'Para el perfil de vendedor tratamos los datos de contacto, el país y la información comercial, de facturación y de entrega que introduces. A las tiendas también se les solicitan datos de la empresa y condiciones de venta. Las funciones de pedidos registran los participantes, los productos, los importes, los estados y los identificadores de pago. En la versión actual, la integración con Stripe está en modo de prueba: no representa un servicio real de cobro ni un depósito en garantía. Cuando utilizas la conexión con Stripe, los datos necesarios para la cuenta y la sesión de pago se transmiten a Stripe. No introduzcas datos de tarjetas ni documentos reales en los flujos de prueba.'],
      ['Fotos, ubicación y funciones opcionales', 'Accedemos a los archivos que eliges subir; no publicamos automáticamente toda tu fototeca. El módulo de eliminación de fondo de la sección de venta procesa la imagen en el dispositivo después de la descarga opcional del modelo; publicar posteriormente la foto es una operación distinta. El mapa de OpenStreetMap se carga al abrirlo y comunica al proveedor tu IP y la zona mostrada. La ubicación GPS se utiliza en el dispositivo solo cuando la activas, para mostrar tu posición en el mapa; el componente no guarda las coordenadas en la base de datos de COSMORA. Las solicitudes cartográficas pueden, aun así, revelar la zona mostrada. Puedes revocar los permisos desde los ajustes del dispositivo y utilizar las demás funciones sin GPS.'],
      ['Asistencia y seguridad', 'Tratamos los mensajes enviados a asistencia, las denuncias y los bloqueos para responder a las solicitudes y combatir los abusos. Los controles automáticos del texto pueden suspender la publicación de un contenido pendiente de revisión; puedes pedir a asistencia que lo revise de nuevo. Las operaciones de seguridad y moderación se basan en el interés legítimo de proteger a los usuarios y al servicio (artículo 6.1.f del RGPD), sin perjuicio del derecho de oposición. Las posibles obligaciones legales se basan en el artículo 6.1.c del RGPD. No envíes contraseñas, códigos temporales ni datos completos de tarjetas a asistencia.'],
      ['Proveedores y datos técnicos', 'Utilizamos Supabase para la autenticación, la base de datos y los archivos, Sites y la infraestructura de Cloudflare para ofrecer el sitio web, y Aruba para el correo de asistencia. Apple, Google, Stripe y OpenStreetMap intervienen cuando utilizas sus respectivas funciones. Las infraestructuras pueden tratar IP, solicitudes y registros técnicos necesarios para el funcionamiento y la seguridad. En el dispositivo se conservan datos de sesión y preferencias técnicas, como el idioma. No utilizamos estos datos para publicidad comportamental. Los servicios externos pueden operar en varios países: no garantizamos que todos los tratamientos se realicen exclusivamente dentro del Espacio Económico Europeo. Puedes solicitar información sobre los destinatarios y las garantías aplicables en info@kreluna.it.'],
      ['Conservación y eliminación', 'La cuenta y los contenidos se conservan mientras mantengas la cuenta o hasta que solicites su eliminación, salvo que sea necesario gestionar operaciones, controversias u obligaciones legales. El plazo de conservación de los datos de asistencia y seguridad depende de la gestión de la solicitud o del incidente y de la necesidad de proteger derechos; los registros y las copias de seguridad también dependen del servicio de infraestructura utilizado. No prometemos la eliminación instantánea de todas las copias de seguridad. Puedes eliminar la cuenta desde la función específica: el proceso elimina la cuenta, los contenidos asociados y los archivos. Si hay operaciones reales pendientes de gestión, el procedimiento exige contactar con asistencia. Si se produce un error al eliminarla, escríbenos para completar la solicitud.'],
      ['Tus derechos', 'En los casos previstos por el RGPD, puedes solicitar el acceso, la rectificación, la eliminación, la limitación y la portabilidad de los datos, y oponerte a los tratamientos basados en el interés legítimo. Cuando un tratamiento se basa en el consentimiento, puedes retirarlo sin afectar a la licitud del tratamiento anterior. Escribe a info@kreluna.it: podríamos pedirte la información estrictamente necesaria para verificar tu identidad. Tienes derecho a presentar una reclamación ante la Autoridad italiana de protección de datos o ante la autoridad competente de tu país.'],
      ['Actualizaciones', 'Actualizaremos este aviso si cambian las funciones o el tratamiento de los datos. En particular, la posible activación de pagos reales requerirá información actualizada antes de su uso. Última actualización: 7 de septiembre de 2026.'],
    ],
  },
};
