'use client';

import { useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, ImagePlus } from 'lucide-react';
import { MobileShell, ScreenHeader } from '@/components/mobile-shell';

export default function NewCommissionPage() {
  const [sent, setSent] = useState(false);
  if (sent) return <MobileShell><div className="flex min-h-dvh flex-col items-center justify-center px-8 text-center"><CheckCircle2 className="size-16 text-emerald-300" /><h1 className="mt-5 text-2xl font-semibold">Request sent</h1><p className="mt-3 text-sm leading-6 text-white/55">Stardust Atelier can now reply with a private quote, deposit, production time and estimated shipping date.</p><Link href="/inbox" className="mt-7 grid h-11 w-full place-items-center rounded-xl bg-gradient-to-r from-pink-500 to-violet-500">Open conversation</Link></div></MobileShell>;
  return <MobileShell><ScreenHeader title="Custom Commission" back="/profile/stardust-atelier" /><form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="space-y-4 px-4 py-5"><div><p className="text-xs font-semibold">Request to Stardust Atelier</p><p className="mt-1 text-[10px] text-white/45">Describe the cosplay, prop or custom work you need.</p></div><label className="grid h-28 place-items-center rounded-xl border border-dashed border-violet-400/40 bg-violet-500/5"><span className="text-center text-[10px] text-white/50"><ImagePlus className="mx-auto mb-2 size-6" />Attach reference images</span><input type="file" multiple accept="image/*" className="sr-only" /></label><textarea required placeholder="Character, materials, details and what should be included" className="checkout-input min-h-32 resize-none py-3" /><div className="grid grid-cols-2 gap-2"><input required type="number" placeholder="Budget (€)" className="checkout-input" /><input required type="date" aria-label="Deadline" className="checkout-input" /></div><div className="grid grid-cols-2 gap-2"><input required placeholder="Size" className="checkout-input" /><select className="checkout-input"><option>Italy</option><option>France</option><option>Germany</option><option>Spain</option><option>Belgium</option><option>Netherlands</option></select></div><input placeholder="Measurements" className="checkout-input" /><button className="h-12 w-full rounded-xl bg-gradient-to-r from-pink-500 to-violet-500 text-sm font-medium">Send Commission Request</button><p className="text-[9px] leading-4 text-white/40">The creator may respond with price, deposit, production time, shipping estimate and terms. No payment is collected at this stage.</p></form></MobileShell>;
}
